/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.mattmoore.tensorflow

import kotlin.test.Test
import kotlin.test.assertTrue

class TensorflowTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Tensorflow()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
